name: "Deploy with Dart Globe"
description: "A reusable GitHub Action to deploy Dart and Flutter applications using Dart Globe CLI"
author: "Mastersam07"
branding:
  icon: "upload-cloud"
  color: "blue"

inputs:
  environment:
    description: "Deployment environment: 'preview' or 'production'"
    default: "preview"
    required: false
  branch:
    description: "Branch to deploy from"
    default: "main"
    required: false
  working-directory:
    description: The working directory in which to run the deployment from
    required: false
    default: .

runs:
  using: "composite"
  steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup Dart SDK
      uses: dart-lang/setup-dart@v1
      with:
        sdk: stable

    - name: Install Dart Globe CLI
      shell: bash
      run: dart pub global activate globe_cli

    - name: Deploy to Preview
      shell: bash
      if: ${{ inputs.environment == 'preview' }}
      working-directory: ${{ inputs.working-directory }}
      run: globe deploy --preview --branch ${{ inputs.branch }}

    - name: Deploy to Production
      shell: bash
      if: ${{ inputs.environment == 'production' }}
      working-directory: ${{ inputs.working-directory }}
      run: globe deploy --production --branch ${{ inputs.branch }}
