name: Test Dart Globe Action

on:
  push:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Run Dart Globe Action
        uses: .
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          globe_token: ${{ secrets.GLOBE_TOKEN }}
          branch: "master"
