name: Test Dart Globe Action

on:
  push:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Run Dart Globe Action
        uses: mastersam07/dart-globe-action@v0.1
        with:
          branch: "master"
